export const FETCHING_EXERCISE_REQUEST = 'FETCHING_EXERCISE_REQUEST';
export const FETCHING_EXERCISE_SUCCESS = 'FETCHING_EXERCISE_SUCCESS';
export const FETCHING_EXERCISE_FAILURE = 'FETCHING_EXERCISE_FAILURE';
export const SEARCH_RESULT_VISIBILITY = 'SEARCH_RESULT_VISIBILITY';